apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-angular.yaml convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: angular-frontend
  name: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: angular-frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-angular.yaml convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: angular-frontend
    spec:
      containers:
        - env:
            - name: CATALINA_OPTS
              value: -Dconfig.apmServerDefault= -Xmx525m
            - name: ET_BACKEND_URL
              value: http://easytravel-backend:8080
          image: dynatrace/easytravel-angular-frontend
          name: angular-frontend
          ports:
            - containerPort: 8080
          resources: {}
      hostname: easytravel-angular-frontend
      restartPolicy: Always
status: {}
